feat(analytics): add createAccount()
HighOutputVentures/highoutput-library pull request #166
Opened 2022-07-13 09:57 UTC by sabmoonie

Add `createAccount()`. This will save user data into Mixpanel.

2022-07-13 22:00 UTC, rogermadjos requested changes

2022-07-13 22:00 UTC, rogermadjos commented on packages/analytics/tests/analytics.spec.ts
> +    const mockAnalytics = {
you should be mocking the mixpanel client

2022-07-13 22:00 UTC, rogermadjos commented on packages/analytics/src/index.ts
> +    accountId: ObjectId;
I think this should be a string

2022-07-14 00:28 UTC, ccpacillos requested changes

2022-07-14 00:28 UTC, ccpacillos commented on packages/analytics/src/index.ts
> +    organizationId?: ObjectId;
I don't think `organiationId` needs to be here. Let's remove this.

2022-07-14 09:13 UTC, ccpacillos requested changes

2022-07-14 09:13 UTC, ccpacillos commented on packages/analytics/tests/analytics.spec.ts
> +describe('analytics', () => {
Kindly change this to `'Analytics'`.

2022-07-14 09:13 UTC, ccpacillos commented on packages/analytics/tests/analytics.spec.ts
> +  test('should create an account', async () => {
Add a second layer of `describe('#createAccount', () => {})`.

2022-07-14 09:39 UTC, ccpacillos approved these changes
Looks good to me.

2022-07-14 10:08 UTC, merged